### ISSUE TITLE
week 3 cult blog post

### ISSUE THREAD

**Issue by gptasinski** [jkarnowski/jkarnowski.github.io#10]
i think we may be the only people tweeting these posts from the Grasshoppers. 

i liked your post, specifically showing how thinking style != learning style. your post reads well
without seeming like i just peaked in your diary, as mine does read. again the visuals were a plus!

**Comment by jkarnowski** [comment]
yeah, why am I not seeing more grasshopper tweets on twitter, it's weird, right? I love sending a short and sweet summary out to the world and exposing my young and raw code!
