### ISSUE TITLE
Hey Jaclyn

### ISSUE THREAD

**Issue by gptasinski** [jkarnowski/jkarnowski.github.io#8]
Just checked out your site. I like the way that you snuck the links to your blogs on your index page and then split them up into the cultural and technical columns in the blog/index. The small font on the index page did make my old man eyes work a little hard, and I was sad I couldn't see the Torres del Paine image. 

Good work, 
Greg

**Comment by jkarnowski** [comment]
Hey! whoa, can't believe I didn't see this issue earlier. I need to get used to looking for them. I have made some major changes so I hope you check out the new site! 
Thanks for the feedback - I don't want your eyes to get wrinkles from my small font. I hope it's bigger now! And, I think TDP shows up now!
